backend:
  name: git-gateway
  branch: main # GitHub 브랜치명

# 사진 저장 경로 (React가 인식할 수 있는 public 폴더 기준)
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "atelier"
    label: "아뜰리에 데이터 관리"
    files:
      - label: "메인 작품 목록"
        name: "products"
        file: "public/data/products.json" # 데이터가 저장될 파일
        fields:
          - label: "작품 리스트"
            name: "items"
            widget: "list"
            fields:
              - {label: "작품명", name: "title", widget: "string"}
              - {label: "대표 사진", name: "image", widget: "image"}
              - {label: "설명", name: "desc", widget: "string"}
